[features]
seeds = false
skip-lint = false
[programs.localnet]
openbook_twap = "4dchEcc6TTC4QVyZQUWgQgcdAsXrUBxsdxpu572BY3Y2"

[[test.genesis]]
address = "opnb2LAfJYbRMAHHvqjCwQxanZn7ReEHp1k81EohpZb"
program = "./tests/fixtures/openbook_v2.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
