[features]
seeds = false
skip-lint = false
[programs.localnet]
openbook_twap = "EgYfg4KUAbXP4UfTrsauxvs75QFf28b3MVEV8qFUGBRh"

[[test.genesis]]
address = "8qkavBpvoHVYkmPhu6QRpXRX39Kcop9uMXvZorBAz43o"
program = "./tests/fixtures/openbook_v2.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
